### ISSUE TITLE
Excluding folders

### ISSUE THREAD

**Issue by cybersiddhu** [chriscortez/twitvault#2]
Its generally good practice to not include some folders  in git that could be easily installed by the package managers.  In this repo, 
both `node_modules` and `bower_components` folders should be excluded from git. Not only these could be easily generated by package mangers but also the included files could be architecture specific, so something generated in mac will not run in linux, something generated in 32bit machines could not run in 64bit machines. Let the package managers handle them, they do not need to be vendored.

**Comment by chriscortez** [comment]
Agreed. Short of registering with npm registry, creating a `modules` folder under `src` seems like a good way to go. I merged this change in pull request #3 into the `master` branch. 

I also removed `bower_components` and created a dependency file in this commit - f5f600178587ed48a2d283687fee4bd17e0b2d9c
